#use wml::debian::translation-check translation="1.2"
<define-tag description>desbordamiento de buffer</define-tag>
<define-tag moreinfo>
<p>Sebastian Schmidt descubrió un error de desbordamiento de
buffer en la función getaddrinfo de Python, que podría provocar que
una dirección IPv6 suministrada por un atacante remoto por medio
de DNS sobreescribiera memoria sobre la pila.</p>

<p>Este error sólo existía en python 2.2 y 2.2.1, y sólo con el
soporte IPv6 activado.  El paquete python2.2 de Debian woody cumple
estas condiciones (el paquete «python» no).</p>

<p>Para la distribución estable (woody), este error se ha corregido
en la versión 2.2.1-4.3.</p>

<p>Este error no afecta a la distribución inestable (sid).</p>

<p>Le recomendamos que actualice el paquete python2.2.</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2004/dsa-458.data"
