#use wml::debian::translation-check translation="1.4" maintainer="Lev Lamberov"
<define-tag description>подделка ответа DNS</define-tag>
<define-tag moreinfo>
<p>В PyDNS, реализации DNS-клиента для языка Python, были обнаружены
многочисленные уязвимости.  Дэн Камински определил
практический вектор подделки ответов DNS и отравления кеша
путём использования ограниченной энтропии в DNS-передаче идентификатора и отсутствии
случайного выбор порта источника UDP во множестве реализаций DNS.  Скотт
Киттерман заметил, что пакет python-dns уязвим к указанным проблемам,
поскольку в нём не выполняется ни случайный выбор идентификатора транзакции, ни случайный выбор порта источника.
Эти две проблемы вместе приводят к тому, что приложения, использующие
python-dns для выполнения запросов DNS, весьма вероятно могут быть подвержены
подделка ответов DNS.</p>

<p>Проект Common Vulnerabilities and Exposures определяет этот
класс уязвимостей как <a href="https://security-tracker.debian.org/tracker/CVE-2008-1447">CVE-2008-1447</a>,
а этот конкретный её образец в PyDNS как <a href="https://security-tracker.debian.org/tracker/CVE-2008-4099">CVE-2008-4099</a>.</p>

<p>В стабильном выпуске (etch) эти проблемы были исправлены в
версии 2.3.0-5.2+etch1.</p>

<p>Рекомендуется обновить пакет python-dns.</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2008/dsa-1619.data"
# $Id$
