#use wml::debian::translation-check translation="1.1" maintainer="Thomas Vincent"
<define-tag description>Initialisation incorrecte du générateur de nombres pseudoaléatoires dans certains cas</define-tag>
<define-tag moreinfo>
<p>Une vulnérabilité de cryptographie a été découverte dans le générateur de
nombres pseudoaléatoires de python-crypto.</p>

<p>Dans certains cas, une situation de compétition pourrait empêcher la
réinitialisation de la graine aléatoire du générateur quand plusieurs processus
sont issus du même parent.
Cela pourrait mener à la génération de sorties identiques pour tous les
processus, ce qui pourrait causer la fuite de valeurs sensibles comme des clés
de chiffrement.</p>

<p>Pour la distribution oldstable (Squeeze), ce problème a été corrigé dans la version 2.1.0-2+squeeze2.</p>

<p>Pour la distribution stable (Wheezy), ce problème a été corrigé dans la version 2.6-4+deb7u3.</p>

<p>Pour la distribution testing (Jessie), ce problème a été corrigé dans la version 2.6.1-2.</p>

<p>Pour la distribution unstable (Sid), ce problème a été corrigé dans la version 2.6.1-1.</p>

<p>Nous vous recommandons de mettre à jour vos paquets python-crypto.</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2013/dsa-2781.data"
# $Id$
