#use wml::debian::translation-check translation="1.2" maintainer="Lev Lamberov"
<define-tag description>несколько проблем</define-tag>
<define-tag moreinfo>
<p>Пол Макмиллан, сотрудники Mozilla и участники основной команды Django обнаружили
несколько уязвимостей в Django, веб-инфраструктуре для языка Python:</p>

<ul>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2011-4136">CVE-2011-4136</a>

  <p>При использовании сессий и кэша на основе памяти сессии Django хранятся
  прямо в корневом пространстве имён кэша. Если пользовательские данные
  хранятся в том же кэше, то удалённый пользователь может перехватить сессию.</p></li>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2011-4137">CVE-2011-4137</a>, <a href="https://security-tracker.debian.org/tracker/CVE-2011-4138">CVE-2011-4138</a>

  <p>По умолчанию тип поля URLfield в Django выполняет проверку переданного URL
  путём отправки запроса, для которого не установлен таймер. При передаче специально
  сформированного URL можно вызвать отказ в обслуживании, соединение будет оставаться
  открытым неопределённо долго, либо будет заполнена память сервера Django.</p></li>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2011-4139">CVE-2011-4139</a>

  <p>Django использует заголовки X-Forwarded-Host для создания полных URL. Этот
  заголовок может не содержать доверенные входные данные и может использоваться
  для отравления кэша.</p></li>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2011-4140">CVE-2011-4140</a>

  <p>Механизм защиты CSRF в Django неправильно обрабатывает настройки
  веб-сервера, поддерживающие произвольные HTTP-заголовки Host,
  что позволяет удалённым злоумышленникам осуществлять неаутентифицированные
  специально сформированные запросы.</p></li>

</ul>

<p>В предыдущем стабильном выпуске (lenny) эта проблема была исправлена в
версии 1.0.2-1+lenny3.</p>

<p>В стабильном выпуске (squeeze) эта проблема была исправлена в
версии 1.2.3-3+squeeze2.</p>

<p>В тестируемом (wheezy) и нестабильном (sid) выпусках эта проблема
была исправлена в версии 1.3.1-1.</p>

<p>Рекомендуется обновить пакеты python-django.</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2011/dsa-2332.data"
# $Id$
