#use wml::debian::translation-check translation="1.1"
<define-tag description>отказ в обслуживании</define-tag>
<define-tag moreinfo>
<p>Фонд ПО Apache (Apache Software Foundation) сообщил, что некоторые
версии mod_python содержит ошибку, которая может при обработке запроса,
содержащего злонамеренную строку, вызвать обвал соответствующего
дочернего процесса Apache. Эта ошибка может быть использована удалённым
нападающим, чтобы вызвать отказ в обслуживании.</p>

<p>В текущем стабильном дистрибутиве (woody) эта проблема исправлена
в версии 2:2.7.8-0.0woody2.</p>

<p>В нестабильном дистрибутиве (sid) эта проблема исправлена
в версии 2:2.7.10-1.</p>

<p>Мы рекомендуем вам обновить пакет libapache-mod-python.</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2004/dsa-452.data"
