#use wml::debian::translation-check translation="1.1" maintainer="Jean-Pierre Giraud"
<define-tag description>Mise à jour de sécurité</define-tag>
<define-tag moreinfo>
<p>James Davis a découvert deux problèmes dans Django, un environnement de
développement web de haut niveau en Python, qui peuvent conduire à une
attaque par déni de service. Un attaquant doté du contrôle sur l'entrée de
la fonction django.utils.html.urlize() ou des méthodes chars() et words()
de django.utils.text.Truncator pourrait fabriquer une chaîne qui pourrait
bloquer l'exécution de l'application.</p>

<p>Pour la distribution oldstable (Jessie), ces problèmes ont été corrigés
dans la version 1.7.11-1+deb8u3.</p>

<p>Pour la distribution stable (Stretch), ces problèmes ont été corrigés
dans la version 1:1.10.7-2+deb9u1.</p>

<p>Nous vous recommandons de mettre à jour vos paquets python-django.</p>

<p>Pour disposer d'un état détaillé sur la sécurité de python-django,
veuillez consulter sa page de suivi de sécurité à l'adresse :
<a href="https://security-tracker.debian.org/tracker/python-django">\
https://security-tracker.debian.org/tracker/python-django</a></p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2018/dsa-4161.data"
# $Id$
