<define-tag description>サービス不能 (DoS) 攻撃</define-tag>
<define-tag moreinfo>
<p>
The Apache Software Foundation  から、一部のバージョンの mod_python 
にバグがあり、不正なクエリ文字列を含むリクエストを処理する際に、対応する 
Apache 子プロセスがクラッシュするとの発表がありました。このバグを使うと、
リモートの攻撃者がサービス不能攻撃を引き起こすことができます。</p>

<p>安定版 (stable) ディストリビューション (woody) では、この問題はバージョン
2:2.7.8-0.0woody2 で修正されています。</p>

<p>不安定版 (unstable) ディストリビューション (sid) では、この問題はバージョン
2:2.7.10-1 で修正されています。</p>

<p>
直ちに libapache-mod-python パッケージをアップグレードすることをお勧めします。
</p>
</define-tag>

#use wml::debian::translation-check translation="1.1"
# do not modify the following line
#include "$(ENGLISHDIR)/security/2004/dsa-452.data"
# $Id$
